@baseUrl = http://localhost:3000


### Get profile
GET {{baseUrl}}/api/profiles/me
Content-Type: application/json
Accept: application/json


### Update profile
PATCH {{baseUrl}}/api/profiles/me
Content-Type: application/json
Accept: application/json

{
  "timezone": "Europe/Warsaw",
  "lastAccount": "card"
}
